### ISSUE TITLE
Keras deleted LambaMerge

### ISSUE THREAD

**Issue by rjsbhatia** [brmson/dataset-sts#38]
Hi, 

I am evaluating existing algorithms for paraphrasing and entailment. I wanted to run para.py, but I am unable to do so. 

Keras have removed LambdaMerge and hence your code doesn't work. I am new to Keras and the topic. 

Here is the link that talks about how to do lamda merge without it. 
https://github.com/fchollet/keras/issues/2342 

Can you update your code?

thanks,

**Comment by pasky** [comment]
Sure!  The work already started in branch f/keras1.0, but it's only at
its beginning. :)  I plan to complete it when I come back from vacation
in 1.5 weeks

**Comment by rjsbhatia** [comment]
I will check in a couple weeks, 
Thanks.
